/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AttractionSwiper: typeof import('./src/components/AttractionSwiper.vue')['default']
    ContextMenu: typeof import('./src/components/base/ContextMenu.vue')['default']
    DeviceTag: typeof import('./src/components/DeviceTag.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    HeaderNav: typeof import('./src/components/Layout/HeaderNav.vue')['default']
    HotRoom: typeof import('./src/components/HotRoom.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Loading: typeof import('./src/components/base/Loading.vue')['default']
    MyButton: typeof import('./src/components/base/MyButton.vue')['default']
    OrderInfoCard: typeof import('./src/components/OrderInfoCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    ThemeChange: typeof import('./src/components/ThemeChange.vue')['default']
    TravellerCard: typeof import('./src/components/TravellerCard.vue')['default']
    UserCenterCard: typeof import('./src/components/UserCenterCard.vue')['default']
  }
}
