/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AttractionSwiper: typeof import('./src/components/AttractionSwiper.vue')['default']
    BaseTitle: typeof import('./src/components/base/BaseTitle.vue')['default']
    CityItem: typeof import('./src/components/base/CityItem.vue')['default']
    ContextMenu: typeof import('./src/components/base/ContextMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElText: typeof import('element-plus/es')['ElText']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HotRoom: typeof import('./src/components/HotRoom.vue')['default']
    Loading: typeof import('./src/components/base/Loading.vue')['default']
    MyButton: typeof import('./src/components/base/MyButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    ThemeChange: typeof import('./src/components/ThemeChange.vue')['default']
    Title: typeof import('./src/components/base/Title.vue')['default']
  }
}
